services:
  cells:
    image: pydio/cells-enterprise:latest
    container_name: cells
    restart: unless-stopped
    ports: 
      - "8080:8080"
    environment:
      - CELLS_INSTALL_YAML=/pydio/config/install.yml
      - CELLS_JOBS_LOG_LEVEL=debug
      - CELLS_LOG=debug
    volumes:
      - cellsdir:/var/cells
      - data:/var/cells/data
      - ./pydio-license:/var/cells/pydio-license:ro
      - ./install-conf.yml:/pydio/config/install.yml:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "--no-check-certificate", "-q", "https://0.0.0.0:8080"]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: cells
      MYSQL_USER: pydio
      MYSQL_PASSWORD: P@ssw0rd
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    volumes:
      - mysqldir:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pP@ssw0rd"]
      interval: 30s
      timeout: 10s
      retries: 3
      
  a3md:
    image: ghcr.io/artefactual-labs/a3m:latest
    container_name: a3md
    ports:
      - "7000:7000"
    volumes:
      - /tmp/preservation:/tmp/preservation:Z
      - /tmp/a3m_completed:/home/a3m/.local/share/a3m/share/completed:Z
    environment:
      - A3M_DEBUG=yes
    user: "1000:1000"  # Allows the container to run with the same user permissions as preservation

  preservation:
    container_name: preservation
    build:
      context: .
    ports:
      - "6905:6905"
    environment:
      - GO_ENV=development
      - PROCESSING_BASE_DIR=/tmp/preservation
      - A3M_COMPLETED_DIR=/home/a3m/.local/share/a3m/share/completed
      - A3M_ADDRESS=a3md:7000
      - CELLS_ADDRESS=https://cells:8080
      - CELLS_ADMIN_TOKEN=${CELLS_ADMIN_TOKEN}
      - LOG_LEVEL=DEBUG
    volumes:
      - preservation_data:/tmp/preservation:rw
      - a3m_completed:/home/a3m/.local/share/a3m/share/completed:rw
    user: "1000:1000"  # Allows the container to run with the same user permissions as a3md
    command: ["./main", "--serve", "--addr=:6905"]
    depends_on:
      cells:
        condition: service_healthy

volumes:
  data:
  cellsdir:
  mysqldir:
  preservation_data:
    driver: local
    driver_opts:
      type: none
      device: /tmp/preservation
      o: bind
  a3m_completed:
    driver: local
    driver_opts:
      type: none
      device: /tmp/a3m_completed
      o: bind