name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: read

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper version information

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxml2-dev \
            pkg-config \
            build-essential

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Build binary
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 1  # Enable CGO for libxml2 bindings
          GOFLAGS: "-buildvcs=true"  # Ensure VCS info is included in the binary
          PKG_CONFIG_PATH: "/usr/lib/pkgconfig"
        run: |
          mkdir -p dist
          # Build with embedded version information
          go build -v \
            -trimpath \
            -o dist/curate-preservation-core \
            .
          
          # Create release archive
          cd dist
          tar czf curate-preservation-core-linux-amd64.tar.gz curate-preservation-core
          sha256sum curate-preservation-core-linux-amd64.tar.gz > curate-preservation-core-linux-amd64.tar.gz.sha256
          cd ..

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/curate-preservation-core-linux-amd64.tar.gz
            dist/curate-preservation-core-linux-amd64.tar.gz.sha256
          generate_release_notes: true
